from typing import Protocol

from orchestrator.models.runtime import RuntimeStatus


class RuntimeProvider(Protocol):
    def create(self, session_id: str, room_id: str) -> RuntimeStatus: ...

    def start(self, session_id: str) -> RuntimeStatus: ...

    def stop(self, session_id: str) -> RuntimeStatus: ...

    def reset(self, session_id: str) -> RuntimeStatus: ...

    def destroy(self, session_id: str) -> RuntimeStatus: ...

    def status(self, session_id: str) -> RuntimeStatus: ...

    def health(self) -> dict[str, str]: ...

    def get_ip(self, session_id: str) -> str | None: ...

